// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	api "github.com/dl-alexandre/UniFi-Site-Manager-CLI/internal/pkg/api"
	mock "github.com/stretchr/testify/mock"
)

// SiteManager is an autogenerated mock type for the SiteManager type
type SiteManager struct {
	mock.Mock
}

// AcknowledgeAlert provides a mock function with given fields: siteID, alertID
func (_m *SiteManager) AcknowledgeAlert(siteID string, alertID string) error {
	ret := _m.Called(siteID, alertID)

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(siteID, alertID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdoptDevice provides a mock function with given fields: siteID, macAddress
func (_m *SiteManager) AdoptDevice(siteID string, macAddress string) error {
	ret := _m.Called(siteID, macAddress)

	if len(ret) == 0 {
		panic("no return value specified for AdoptDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(siteID, macAddress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArchiveAlert provides a mock function with given fields: siteID, alertID
func (_m *SiteManager) ArchiveAlert(siteID string, alertID string) error {
	ret := _m.Called(siteID, alertID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(siteID, alertID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BlockClient provides a mock function with given fields: siteID, macAddress, block
func (_m *SiteManager) BlockClient(siteID string, macAddress string, block bool) error {
	ret := _m.Called(siteID, macAddress, block)

	if len(ret) == 0 {
		panic("no return value specified for BlockClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = rf(siteID, macAddress, block)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSite provides a mock function with given fields: req
func (_m *SiteManager) CreateSite(req api.CreateSiteRequest) (*api.SingleResponse[api.Site], error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSite")
	}

	var r0 *api.SingleResponse[api.Site]
	var r1 error
	if rf, ok := ret.Get(0).(func(api.CreateSiteRequest) (*api.SingleResponse[api.Site], error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(api.CreateSiteRequest) *api.SingleResponse[api.Site]); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.Site])
		}
	}

	if rf, ok := ret.Get(1).(func(api.CreateSiteRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateWLAN provides a mock function with given fields: siteID, req
func (_m *SiteManager) CreateWLAN(siteID string, req api.CreateWLANRequest) (*api.SingleResponse[api.WLAN], error) {
	ret := _m.Called(siteID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateWLAN")
	}

	var r0 *api.SingleResponse[api.WLAN]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, api.CreateWLANRequest) (*api.SingleResponse[api.WLAN], error)); ok {
		return rf(siteID, req)
	}
	if rf, ok := ret.Get(0).(func(string, api.CreateWLANRequest) *api.SingleResponse[api.WLAN]); ok {
		r0 = rf(siteID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.WLAN])
		}
	}

	if rf, ok := ret.Get(1).(func(string, api.CreateWLANRequest) error); ok {
		r1 = rf(siteID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSite provides a mock function with given fields: siteID
func (_m *SiteManager) DeleteSite(siteID string) error {
	ret := _m.Called(siteID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(siteID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWLAN provides a mock function with given fields: siteID, wlanID
func (_m *SiteManager) DeleteWLAN(siteID string, wlanID string) error {
	ret := _m.Called(siteID, wlanID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWLAN")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(siteID, wlanID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetClientStats provides a mock function with given fields: siteID, macAddress
func (_m *SiteManager) GetClientStats(siteID string, macAddress string) (*api.SingleResponse[api.ClientStats], error) {
	ret := _m.Called(siteID, macAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetClientStats")
	}

	var r0 *api.SingleResponse[api.ClientStats]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*api.SingleResponse[api.ClientStats], error)); ok {
		return rf(siteID, macAddress)
	}
	if rf, ok := ret.Get(0).(func(string, string) *api.SingleResponse[api.ClientStats]); ok {
		r0 = rf(siteID, macAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.ClientStats])
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(siteID, macAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDevice provides a mock function with given fields: siteID, deviceID
func (_m *SiteManager) GetDevice(siteID string, deviceID string) (*api.SingleResponse[api.Device], error) {
	ret := _m.Called(siteID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetDevice")
	}

	var r0 *api.SingleResponse[api.Device]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*api.SingleResponse[api.Device], error)); ok {
		return rf(siteID, deviceID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *api.SingleResponse[api.Device]); ok {
		r0 = rf(siteID, deviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.Device])
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(siteID, deviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHost provides a mock function with given fields: hostID
func (_m *SiteManager) GetHost(hostID string) (*api.SingleResponse[api.Host], error) {
	ret := _m.Called(hostID)

	if len(ret) == 0 {
		panic("no return value specified for GetHost")
	}

	var r0 *api.SingleResponse[api.Host]
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*api.SingleResponse[api.Host], error)); ok {
		return rf(hostID)
	}
	if rf, ok := ret.Get(0).(func(string) *api.SingleResponse[api.Host]); ok {
		r0 = rf(hostID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.Host])
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hostID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHostHealth provides a mock function with given fields: hostID
func (_m *SiteManager) GetHostHealth(hostID string) (*api.HealthResponse, error) {
	ret := _m.Called(hostID)

	if len(ret) == 0 {
		panic("no return value specified for GetHostHealth")
	}

	var r0 *api.HealthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*api.HealthResponse, error)); ok {
		return rf(hostID)
	}
	if rf, ok := ret.Get(0).(func(string) *api.HealthResponse); ok {
		r0 = rf(hostID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.HealthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hostID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHostStats provides a mock function with given fields: hostID, period
func (_m *SiteManager) GetHostStats(hostID string, period string) (*api.SingleResponse[api.PerformanceStats], error) {
	ret := _m.Called(hostID, period)

	if len(ret) == 0 {
		panic("no return value specified for GetHostStats")
	}

	var r0 *api.SingleResponse[api.PerformanceStats]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*api.SingleResponse[api.PerformanceStats], error)); ok {
		return rf(hostID, period)
	}
	if rf, ok := ret.Get(0).(func(string, string) *api.SingleResponse[api.PerformanceStats]); ok {
		r0 = rf(hostID, period)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.PerformanceStats])
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(hostID, period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSite provides a mock function with given fields: siteID
func (_m *SiteManager) GetSite(siteID string) (*api.SingleResponse[api.Site], error) {
	ret := _m.Called(siteID)

	if len(ret) == 0 {
		panic("no return value specified for GetSite")
	}

	var r0 *api.SingleResponse[api.Site]
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*api.SingleResponse[api.Site], error)); ok {
		return rf(siteID)
	}
	if rf, ok := ret.Get(0).(func(string) *api.SingleResponse[api.Site]); ok {
		r0 = rf(siteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.Site])
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(siteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSiteHealth provides a mock function with given fields: siteID
func (_m *SiteManager) GetSiteHealth(siteID string) (*api.HealthResponse, error) {
	ret := _m.Called(siteID)

	if len(ret) == 0 {
		panic("no return value specified for GetSiteHealth")
	}

	var r0 *api.HealthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*api.HealthResponse, error)); ok {
		return rf(siteID)
	}
	if rf, ok := ret.Get(0).(func(string) *api.HealthResponse); ok {
		r0 = rf(siteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.HealthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(siteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSiteStats provides a mock function with given fields: siteID, period
func (_m *SiteManager) GetSiteStats(siteID string, period string) (*api.SingleResponse[api.PerformanceStats], error) {
	ret := _m.Called(siteID, period)

	if len(ret) == 0 {
		panic("no return value specified for GetSiteStats")
	}

	var r0 *api.SingleResponse[api.PerformanceStats]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*api.SingleResponse[api.PerformanceStats], error)); ok {
		return rf(siteID, period)
	}
	if rf, ok := ret.Get(0).(func(string, string) *api.SingleResponse[api.PerformanceStats]); ok {
		r0 = rf(siteID, period)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.PerformanceStats])
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(siteID, period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWLAN provides a mock function with given fields: siteID, wlanID
func (_m *SiteManager) GetWLAN(siteID string, wlanID string) (*api.SingleResponse[api.WLAN], error) {
	ret := _m.Called(siteID, wlanID)

	if len(ret) == 0 {
		panic("no return value specified for GetWLAN")
	}

	var r0 *api.SingleResponse[api.WLAN]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*api.SingleResponse[api.WLAN], error)); ok {
		return rf(siteID, wlanID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *api.SingleResponse[api.WLAN]); ok {
		r0 = rf(siteID, wlanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.WLAN])
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(siteID, wlanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAlerts provides a mock function with given fields: siteID, pageSize, nextToken, archived
func (_m *SiteManager) ListAlerts(siteID string, pageSize int, nextToken string, archived bool) (*api.ListResponse[api.Alert], error) {
	ret := _m.Called(siteID, pageSize, nextToken, archived)

	if len(ret) == 0 {
		panic("no return value specified for ListAlerts")
	}

	var r0 *api.ListResponse[api.Alert]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, string, bool) (*api.ListResponse[api.Alert], error)); ok {
		return rf(siteID, pageSize, nextToken, archived)
	}
	if rf, ok := ret.Get(0).(func(string, int, string, bool) *api.ListResponse[api.Alert]); ok {
		r0 = rf(siteID, pageSize, nextToken, archived)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ListResponse[api.Alert])
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, string, bool) error); ok {
		r1 = rf(siteID, pageSize, nextToken, archived)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListClients provides a mock function with given fields: siteID, pageSize, nextToken, wiredOnly, wirelessOnly
func (_m *SiteManager) ListClients(siteID string, pageSize int, nextToken string, wiredOnly bool, wirelessOnly bool) (*api.ListResponse[api.NetworkClient], error) {
	ret := _m.Called(siteID, pageSize, nextToken, wiredOnly, wirelessOnly)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 *api.ListResponse[api.NetworkClient]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, string, bool, bool) (*api.ListResponse[api.NetworkClient], error)); ok {
		return rf(siteID, pageSize, nextToken, wiredOnly, wirelessOnly)
	}
	if rf, ok := ret.Get(0).(func(string, int, string, bool, bool) *api.ListResponse[api.NetworkClient]); ok {
		r0 = rf(siteID, pageSize, nextToken, wiredOnly, wirelessOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ListResponse[api.NetworkClient])
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, string, bool, bool) error); ok {
		r1 = rf(siteID, pageSize, nextToken, wiredOnly, wirelessOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDevices provides a mock function with given fields: siteID, pageSize, nextToken
func (_m *SiteManager) ListDevices(siteID string, pageSize int, nextToken string) (*api.ListResponse[api.Device], error) {
	ret := _m.Called(siteID, pageSize, nextToken)

	if len(ret) == 0 {
		panic("no return value specified for ListDevices")
	}

	var r0 *api.ListResponse[api.Device]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, string) (*api.ListResponse[api.Device], error)); ok {
		return rf(siteID, pageSize, nextToken)
	}
	if rf, ok := ret.Get(0).(func(string, int, string) *api.ListResponse[api.Device]); ok {
		r0 = rf(siteID, pageSize, nextToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ListResponse[api.Device])
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, string) error); ok {
		r1 = rf(siteID, pageSize, nextToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEvents provides a mock function with given fields: siteID, pageSize, nextToken
func (_m *SiteManager) ListEvents(siteID string, pageSize int, nextToken string) (*api.ListResponse[api.Event], error) {
	ret := _m.Called(siteID, pageSize, nextToken)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 *api.ListResponse[api.Event]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, string) (*api.ListResponse[api.Event], error)); ok {
		return rf(siteID, pageSize, nextToken)
	}
	if rf, ok := ret.Get(0).(func(string, int, string) *api.ListResponse[api.Event]); ok {
		r0 = rf(siteID, pageSize, nextToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ListResponse[api.Event])
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, string) error); ok {
		r1 = rf(siteID, pageSize, nextToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListHosts provides a mock function with given fields: pageSize, nextToken
func (_m *SiteManager) ListHosts(pageSize int, nextToken string) (*api.ListResponse[api.Host], error) {
	ret := _m.Called(pageSize, nextToken)

	if len(ret) == 0 {
		panic("no return value specified for ListHosts")
	}

	var r0 *api.ListResponse[api.Host]
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (*api.ListResponse[api.Host], error)); ok {
		return rf(pageSize, nextToken)
	}
	if rf, ok := ret.Get(0).(func(int, string) *api.ListResponse[api.Host]); ok {
		r0 = rf(pageSize, nextToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ListResponse[api.Host])
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(pageSize, nextToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListNetworks provides a mock function with given fields: siteID, pageSize, nextToken
func (_m *SiteManager) ListNetworks(siteID string, pageSize int, nextToken string) (*api.ListResponse[api.Network], error) {
	ret := _m.Called(siteID, pageSize, nextToken)

	if len(ret) == 0 {
		panic("no return value specified for ListNetworks")
	}

	var r0 *api.ListResponse[api.Network]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, string) (*api.ListResponse[api.Network], error)); ok {
		return rf(siteID, pageSize, nextToken)
	}
	if rf, ok := ret.Get(0).(func(string, int, string) *api.ListResponse[api.Network]); ok {
		r0 = rf(siteID, pageSize, nextToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ListResponse[api.Network])
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, string) error); ok {
		r1 = rf(siteID, pageSize, nextToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSites provides a mock function with given fields: pageSize, nextToken
func (_m *SiteManager) ListSites(pageSize int, nextToken string) (*api.ListResponse[api.Site], error) {
	ret := _m.Called(pageSize, nextToken)

	if len(ret) == 0 {
		panic("no return value specified for ListSites")
	}

	var r0 *api.ListResponse[api.Site]
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (*api.ListResponse[api.Site], error)); ok {
		return rf(pageSize, nextToken)
	}
	if rf, ok := ret.Get(0).(func(int, string) *api.ListResponse[api.Site]); ok {
		r0 = rf(pageSize, nextToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ListResponse[api.Site])
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(pageSize, nextToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWLANs provides a mock function with given fields: siteID, pageSize, nextToken
func (_m *SiteManager) ListWLANs(siteID string, pageSize int, nextToken string) (*api.ListResponse[api.WLAN], error) {
	ret := _m.Called(siteID, pageSize, nextToken)

	if len(ret) == 0 {
		panic("no return value specified for ListWLANs")
	}

	var r0 *api.ListResponse[api.WLAN]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, string) (*api.ListResponse[api.WLAN], error)); ok {
		return rf(siteID, pageSize, nextToken)
	}
	if rf, ok := ret.Get(0).(func(string, int, string) *api.ListResponse[api.WLAN]); ok {
		r0 = rf(siteID, pageSize, nextToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ListResponse[api.WLAN])
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, string) error); ok {
		r1 = rf(siteID, pageSize, nextToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestartDevice provides a mock function with given fields: siteID, deviceID
func (_m *SiteManager) RestartDevice(siteID string, deviceID string) error {
	ret := _m.Called(siteID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for RestartDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(siteID, deviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestartHost provides a mock function with given fields: hostID
func (_m *SiteManager) RestartHost(hostID string) error {
	ret := _m.Called(hostID)

	if len(ret) == 0 {
		panic("no return value specified for RestartHost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(hostID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSite provides a mock function with given fields: siteID, req
func (_m *SiteManager) UpdateSite(siteID string, req api.UpdateSiteRequest) (*api.SingleResponse[api.Site], error) {
	ret := _m.Called(siteID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSite")
	}

	var r0 *api.SingleResponse[api.Site]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, api.UpdateSiteRequest) (*api.SingleResponse[api.Site], error)); ok {
		return rf(siteID, req)
	}
	if rf, ok := ret.Get(0).(func(string, api.UpdateSiteRequest) *api.SingleResponse[api.Site]); ok {
		r0 = rf(siteID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.Site])
		}
	}

	if rf, ok := ret.Get(1).(func(string, api.UpdateSiteRequest) error); ok {
		r1 = rf(siteID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWLAN provides a mock function with given fields: siteID, wlanID, req
func (_m *SiteManager) UpdateWLAN(siteID string, wlanID string, req api.UpdateWLANRequest) (*api.SingleResponse[api.WLAN], error) {
	ret := _m.Called(siteID, wlanID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWLAN")
	}

	var r0 *api.SingleResponse[api.WLAN]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, api.UpdateWLANRequest) (*api.SingleResponse[api.WLAN], error)); ok {
		return rf(siteID, wlanID, req)
	}
	if rf, ok := ret.Get(0).(func(string, string, api.UpdateWLANRequest) *api.SingleResponse[api.WLAN]); ok {
		r0 = rf(siteID, wlanID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.WLAN])
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, api.UpdateWLANRequest) error); ok {
		r1 = rf(siteID, wlanID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpgradeDevice provides a mock function with given fields: siteID, deviceID
func (_m *SiteManager) UpgradeDevice(siteID string, deviceID string) error {
	ret := _m.Called(siteID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for UpgradeDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(siteID, deviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Whoami provides a mock function with no fields
func (_m *SiteManager) Whoami() (*api.SingleResponse[api.UserInfo], error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 *api.SingleResponse[api.UserInfo]
	var r1 error
	if rf, ok := ret.Get(0).(func() (*api.SingleResponse[api.UserInfo], error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *api.SingleResponse[api.UserInfo]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SingleResponse[api.UserInfo])
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnableDebug provides a mock function
func (_m *SiteManager) EnableDebug() {
	_m.Called()
}

// GetConnectionInfo provides a mock function
func (_m *SiteManager) GetConnectionInfo() api.ConnectionInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionInfo")
	}

	var r0 api.ConnectionInfo
	if rf, ok := ret.Get(0).(func() api.ConnectionInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(api.ConnectionInfo)
	}

	return r0
}

// NewSiteManager creates a new instance of SiteManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSiteManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *SiteManager {
	mock := &SiteManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
